name: Run Cloud ETL

on:
  workflow_dispatch:  # Manual trigger
  schedule:
    - cron: '5 * * * *'  # Every day at 5:00 AM IST (11:30 PM UTC)

jobs:
  run-etl:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: 3.9

    - name: Install dependencies
      run: |
        pip install -r requirements.txt

    - name: Create GCP credentials file
      run: |
        echo "$GCP_CREDS" > gcp-creds.json
      env:
        GCP_CREDS: ${{ secrets.GCP_CREDS }}

    - name: Run ETL job
      env:
        GOOGLE_APPLICATION_CREDENTIALS: gcp-creds.json
      run: |
        python etl.py
